package modelo.pojo;
// Generated 1/02/2017 08:05:29 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private int id;
     private String nombreTabla;
     private Long idCampo;
     private String nombreCampo;
     private String valorAnterior;
     private String valorNuevo;
     private Date fechaOperacion;
     private Character tipoOperacion;
     private Serializable ip;

    public Auditoria() {
    }

	
    public Auditoria(int id) {
        this.id = id;
    }
    public Auditoria(int id, String nombreTabla, Long idCampo, String nombreCampo, String valorAnterior, String valorNuevo, Date fechaOperacion, Character tipoOperacion, Serializable ip) {
       this.id = id;
       this.nombreTabla = nombreTabla;
       this.idCampo = idCampo;
       this.nombreCampo = nombreCampo;
       this.valorAnterior = valorAnterior;
       this.valorNuevo = valorNuevo;
       this.fechaOperacion = fechaOperacion;
       this.tipoOperacion = tipoOperacion;
       this.ip = ip;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreTabla() {
        return this.nombreTabla;
    }
    
    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }
    public Long getIdCampo() {
        return this.idCampo;
    }
    
    public void setIdCampo(Long idCampo) {
        this.idCampo = idCampo;
    }
    public String getNombreCampo() {
        return this.nombreCampo;
    }
    
    public void setNombreCampo(String nombreCampo) {
        this.nombreCampo = nombreCampo;
    }
    public String getValorAnterior() {
        return this.valorAnterior;
    }
    
    public void setValorAnterior(String valorAnterior) {
        this.valorAnterior = valorAnterior;
    }
    public String getValorNuevo() {
        return this.valorNuevo;
    }
    
    public void setValorNuevo(String valorNuevo) {
        this.valorNuevo = valorNuevo;
    }
    public Date getFechaOperacion() {
        return this.fechaOperacion;
    }
    
    public void setFechaOperacion(Date fechaOperacion) {
        this.fechaOperacion = fechaOperacion;
    }
    public Character getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(Character tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }
    public Serializable getIp() {
        return this.ip;
    }
    
    public void setIp(Serializable ip) {
        this.ip = ip;
    }




}


