package modelo.pojo;
// Generated 1/02/2017 08:05:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Camposhansa generated by hbm2java
 */
public class Camposhansa  implements java.io.Serializable {


     private int idtblhansa;
     private String idfactura;
     private String corr;
     private String paciente;
     private String medico;
     private String sede;
     private String nocedula;
     private String estado;
     private Boolean sexo;
     private Date fechanac;
     private Set histopatologias = new HashSet(0);
     private Set citologias = new HashSet(0);

    public Camposhansa() {
    }

	
    public Camposhansa(int idtblhansa, String idfactura) {
        this.idtblhansa = idtblhansa;
        this.idfactura = idfactura;
    }
    public Camposhansa(int idtblhansa, String idfactura, String corr, String paciente, String medico, String sede, String nocedula, String estado, Boolean sexo, Date fechanac, Set histopatologias, Set citologias) {
       this.idtblhansa = idtblhansa;
       this.idfactura = idfactura;
       this.corr = corr;
       this.paciente = paciente;
       this.medico = medico;
       this.sede = sede;
       this.nocedula = nocedula;
       this.estado = estado;
       this.sexo = sexo;
       this.fechanac = fechanac;
       this.histopatologias = histopatologias;
       this.citologias = citologias;
    }
   
    public int getIdtblhansa() {
        return this.idtblhansa;
    }
    
    public void setIdtblhansa(int idtblhansa) {
        this.idtblhansa = idtblhansa;
    }
    public String getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(String idfactura) {
        this.idfactura = idfactura;
    }
    public String getCorr() {
        return this.corr;
    }
    
    public void setCorr(String corr) {
        this.corr = corr;
    }
    public String getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(String paciente) {
        this.paciente = paciente;
    }
    public String getMedico() {
        return this.medico;
    }
    
    public void setMedico(String medico) {
        this.medico = medico;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public String getNocedula() {
        return this.nocedula;
    }
    
    public void setNocedula(String nocedula) {
        this.nocedula = nocedula;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Boolean sexo) {
        this.sexo = sexo;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public Set getHistopatologias() {
        return this.histopatologias;
    }
    
    public void setHistopatologias(Set histopatologias) {
        this.histopatologias = histopatologias;
    }
    public Set getCitologias() {
        return this.citologias;
    }
    
    public void setCitologias(Set citologias) {
        this.citologias = citologias;
    }




}


