package modelo.pojo;
// Generated 1/02/2017 08:05:29 AM by Hibernate Tools 4.3.1



/**
 * Perfilporpermiso generated by hbm2java
 */
public class Perfilporpermiso  implements java.io.Serializable {


     private int idtblperfilxpermiso;
     private Perfiles perfiles;
     private Permisos permisos;
     private boolean estado;

    public Perfilporpermiso() {
    }

    public Perfilporpermiso(int idtblperfilxpermiso, Perfiles perfiles, Permisos permisos, boolean estado) {
       this.idtblperfilxpermiso = idtblperfilxpermiso;
       this.perfiles = perfiles;
       this.permisos = permisos;
       this.estado = estado;
    }
   
    public int getIdtblperfilxpermiso() {
        return this.idtblperfilxpermiso;
    }
    
    public void setIdtblperfilxpermiso(int idtblperfilxpermiso) {
        this.idtblperfilxpermiso = idtblperfilxpermiso;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


